### ISSUE TITLE
labelcolor not set when used hex value

### ISSUE THREAD

**Issue by kheek** [RBVI/enhancedGraphics#6]
Hi,  first of all I need to say I'm very, very happy with enhancedgrpahics!

I've a small issue, using the label I can't set the colorvalue using a hex string e.g. "#ff0000"

Best regards,
Klaas Heek

**Comment by kheek** [comment]
It's not an Issue but more a question/request... it would be really wonderfull if you could add 'svg' images to nodes. I think you're close to that... passthrough of a svg path, with forecolor, transparancy and backgroundcolor (as if it was a diagram) would be a real improvement for Cytoscape users.

**Comment by marclegeay** [comment]
Hi Klaas,

Regarding your label color issue: which chart are you using?
If you are using the label, then there was a mistake in the README that I just fixed, you don't have to use 'labelcolor' but just 'color'.
I tested with the bar, circos, label, and pie: it works with hex colors.
The only one that did not work was with heatstrips, where the color was always black (hex or non-hex label color values were just ignored).
The other charts do not use label colors.

Regarding your request about svg images, this is something we have to discuss with the other developers and we thank you for your idea.

Best,
Marc.

**Comment by kheek** [comment]
> Hi Klaas,
> 
> Regarding your label color issue: which chart are you using?
> If you are using the label, then there was a mistake in the README that I just fixed, you don't have to use 'labelcolor' but just 'color'.
> I tested with the bar, circos, label, and pie: it works with hex colors.
> The only one that did not work was with heatstrips, where the color was always black (hex or non-hex label color values were just ignored).
> The other charts do not use label colors.
> 
> Regarding your request about svg images, this is something we have to discuss with the other developers and we thank you for your idea.
> 
> Best,
> Marc.

Hi Marc,

Thanks for the fast response. I use the label without a graph. E.g. in this way:

"label: attribute=name labelsize=10 outline=true background=true color=white dropShadow=true"
 But when I change 'white'  to eg: #ff0000 in this way:
"label: attribute=name labelsize=10 outline=true background=true color=#ff0000 dropShadow=true"
it stays black in stead of red.
Best regards,
Klaas

**Comment by marclegeay** [comment]
You should put string parameters into quotes, so that you are sure not to have issues.

Try `label: attribute="name" labelsize=10 outline=true background=true color="#ff0000" dropShadow=true`.

**Comment by kheek** [comment]
Yes! Thank you very much... found a workaround for the svg 'image' by placing the svg icon in a font as shape1 (background image 1) and the node text as shape 2.  In this way I can export the complete cytoscape graph as a SVG in stead of using png images! Thanks again!
